// 100 câu nói hay về cuộc sống, tình mẹ, con cái, cha mẹ
export const QUOTES = [
    // --- Tình mẫu tử & Con cái ---
    "Vũ trụ không có nhiều kì quan, nhưng kì quan tuyệt diệu nhất là trái tim người mẹ.",
    "Bàn tay đưa nôi là bàn tay thống trị cả thế giới.",
    "Tình yêu của người mẹ dành cho con không giống bất kỳ điều gì khác trên thế giới. Nó không biết đến luật lệ hay sự thương hại.",
    "Mọi hạnh phúc trên đời này đều bắt đầu từ nụ cười của con.",
    "Con là món quà tuyệt vời nhất mà cuộc đời đã ban tặng cho mẹ.",
    "Trong mắt con, mẹ là cả thế giới. Trong mắt mẹ, con là cả cuộc đời.",
    "Không có tình yêu nào vĩ đại và vô điều kiện như tình yêu của mẹ dành cho con.",
    "Mẹ là người có thể thay thế bất kỳ ai khác, nhưng không ai có thể thay thế được mẹ.",
    "Làm mẹ không phải là một công việc, đó là một đặc ân tuyệt vời của cuộc sống.",
    "Hạnh phúc của người mẹ là được nhìn thấy con lớn khôn khỏe mạnh mỗi ngày.",
    "Nụ cười của con là liều thuốc chữa lành mọi mệt mỏi trong cuộc sống của mẹ.",
    "Mẹ có thể chưa hoàn hảo, nhưng mẹ luôn yêu con theo cách hoàn hảo nhất.",
    "Bông hoa đẹp nhất trên thế giới này chính là nụ cười của con yêu.",
    "Khi con chào đời, mẹ cũng được sinh ra một lần nữa với tư cách là một người mẹ.",
    "Không có gì ngọt ngào bằng tiếng gọi 'Mẹ ơi' của con trẻ.",
    "Tình yêu của mẹ là nguồn năng lượng cho phép một người bình thường làm nên những điều phi thường.",
    "Dù con có lớn khôn thế nào, trong lòng mẹ con vẫn mãi là đứa con bé bỏng.",
    "Trái tim người mẹ là trường học của đứa con.",
    "Mẹ là người nâng đỡ con khi con vấp ngã và là người ăn mừng chiến thắng của con nồng nhiệt nhất.",
    "Có con là điều kỳ diệu nhất mà cuộc sống đã mang lại cho cha mẹ.",
    "Tình mẫu tử là sợi dây liên kết thiêng liêng nhất, không bao giờ có thể bị chia cắt.",
    "Chỉ khi làm mẹ, người ta mới hiểu thế nào là yêu thương vô điều kiện.",
    "Mẹ là bến đỗ bình yên nhất sau những giông bão của cuộc đời.",
    "Những giọt nước mắt của mẹ có thể làm dịu đi mọi nỗi đau của con.",
    "Con là động lực lớn nhất để mẹ phấn đấu trở thành phiên bản tốt hơn của chính mình.",

    // --- Cha mẹ & Gia đình ---
    "Gia đình là nơi cuộc sống bắt đầu và tình yêu không bao giờ kết thúc.",
    "Đi khắp thế gian không ai tốt bằng mẹ, gánh nặng cuộc đời không ai khổ bằng cha.",
    "Cha mẹ là những người duy nhất yêu thương bạn mà không cần điều kiện.",
    "Tình yêu của cha mẹ dành cho con cái là vĩnh cửu, vượt qua mọi giới hạn thời gian.",
    "Gia đình không phải là một điều quan trọng, nó là tất cả mọi thứ.",
    "Cha là chỗ dựa vững chãi, mẹ là dòng nước mát lành nuôi dưỡng tâm hồn con.",
    "Nhà không cần quá lớn, chỉ cần trong đó có đủ tình yêu thương của cha mẹ và tiếng cười của con trẻ.",
    "Sự hy sinh của cha mẹ là bệ phóng cho những ước mơ của con cái bay cao.",
    "Tình yêu của cha rộng lớn như núi non, tình yêu của mẹ bao la như biển cả.",
    "Gia đình là trường học đầu tiên và cha mẹ là những người thầy đầu tiên của con.",
    "Dù thế giới ngoài kia có quay lưng với bạn, gia đình vẫn luôn mở rộng vòng tay đón bạn trở về.",
    "Hạnh phúc nhất là khi nhìn thấy cha mẹ khỏe mạnh và vui cười mỗi ngày.",
    "Hãy yêu thương cha mẹ khi còn có thể, vì chúng ta không bao giờ biết họ sẽ ở bên ta bao lâu.",
    "Công lao của cha mẹ tựa như trời biển, cả đời con cũng không thể đáp đền hết.",
    "Nhà là nơi bão dừng sau cánh cửa, nơi có cha mẹ đứng chờ con về.",
    "Tình cảm gia đình là liều thuốc tốt nhất cho mọi vết thương lòng.",
    "Không có sự giáo dục nào tốt hơn tấm gương phản chiếu từ tình yêu thương của cha mẹ.",
    "Gia đình là nơi bạn được là chính mình nhất và được yêu thương nhiều nhất.",
    "Lòng biết ơn đối với cha mẹ là cội nguồn của mọi đức hạnh.",
    "Cha mẹ cho con hình hài, cuộc đời cho con bài học, nhưng gia đình cho con tình yêu.",
    "Nước biển mênh mông không đong đầy tình mẹ, mây trời lồng lộng không phủ kín công cha.",
    "Sự bình yên lớn nhất của đời người là biết cha mẹ ở quê nhà vẫn bình an.",
    "Hãy đối xử tốt với cha mẹ, vì họ đã dành cả thanh xuân để đổi lấy tương lai của bạn.",
    "Gia đình là điểm tựa vững chắc nhất để con tự tin vững bước vào đời.",
    "Tình yêu thương của cha mẹ là ánh sáng soi đường cho con trong những đêm tối tăm.",

    // --- Ý nghĩa cuộc sống & Cảm hứng ---
    "Hãy sống như một đóa hoa, rực rỡ và ngát hương theo cách của riêng mình.",
    "Cuộc sống không phải là chờ đợi giông bão đi qua, mà là học cách nhảy múa dưới cơn mưa.",
    "Mỗi ngày mới là một cơ hội để bạn viết nên một chương mới cho cuộc đời mình.",
    "Hãy biết ơn những gì bạn đang có; bạn sẽ nhận được nhiều hơn.",
    "Sự kiên nhẫn và thời gian có thể làm được nhiều điều hơn là sức mạnh hay sự giận dữ.",
    "Đừng so sánh cuộc đời mình với người khác, vì mỗi loài hoa đều có thời điểm nở rộ riêng.",
    "Cuộc sống rất ngắn ngủi, hãy tập trung vào những điều thực sự quan trọng và mang lại hạnh phúc.",
    "Cách tốt nhất để dự đoán tương lai là tự mình tạo ra nó.",
    "Mỗi khó khăn đi qua đều để lại cho ta một bài học quý giá và sự trưởng thành.",
    "Hãy tử tế với tất cả những người bạn gặp, vì ai cũng đang chiến đấu với một cuộc chiến của riêng họ.",
    "Hạnh phúc không phải là điểm đến, mà là một hành trình ta đang đi.",
    "Hãy luôn giữ nụ cười trên môi, vì cuộc sống là một điều tuyệt đẹp và có rất nhiều điều để mỉm cười.",
    "Thành công không phải là chìa khóa mở cánh cửa hạnh phúc. Hạnh phúc mới là chìa khóa dẫn đến thành công.",
    "Đừng để những tiếc nuối của ngày hôm qua làm lu mờ vẻ đẹp của ngày hôm nay.",
    "Sống trọn vẹn từng khoảnh khắc, vì thời gian trôi đi sẽ không bao giờ trở lại.",
    "Một thái độ tích cực có thể thay đổi hoàn toàn cục diện của một ngày tồi tệ.",
    "Hãy lắng nghe tiếng nói bên trong tâm hồn bạn và dũng cảm đi theo con đường mình chọn.",
    "Món quà lớn nhất bạn có thể trao cho ai đó là sự hiện diện và sự lắng nghe chân thành của bạn.",
    "Sự bình yên trong tâm hồn là tài sản vô giá nhất của một con người.",
    "Hãy gieo hạt giống yêu thương mỗi ngày, bạn sẽ thu hoạch được một vườn hoa hạnh phúc.",
    "Cuộc sống là một bức tranh vẽ tuyệt đẹp, hãy dùng những gam màu tươi sáng nhất để tô điểm nó.",
    "Đừng sợ thất bại, hãy sợ việc đứng yên một chỗ và không dám thử sức.",
    "Mỗi người xuất hiện trong cuộc đời bạn đều có một lý do, hoặc là để trao yêu thương, hoặc là dạy bạn bài học.",
    "Hãy học cách buông bỏ những điều không thể thay đổi để đón nhận những điều tốt đẹp hơn đang tới.",
    "Chỉ cần bạn không bỏ cuộc, mỗi bước đi dù nhỏ cũng đưa bạn đến gần hơn với ước mơ.",

    // --- Thai kỳ, Làm mẹ & Niềm hy vọng ---
    "Có một sinh linh nhỏ bé đang lớn lên bên dưới trái tim mẹ, đó là điều kỳ diệu thiêng liêng nhất.",
    "Chín tháng mười ngày mang nặng đẻ đau là hành trình chứng minh sự vĩ đại của người phụ nữ.",
    "Mỗi nhịp đập nhẹ nhàng của con trong bụng mẹ là một lời thì thầm: 'Con yêu mẹ nhiều lắm'.",
    "Mẹ đang bảo vệ một thiên thần nhỏ, và thiên thần đó cũng đang sưởi ấm tâm hồn mẹ.",
    "Làm mẹ là hành trình học hỏi, trưởng thành và yêu thương không ngừng nghỉ.",
    "Cơ thể của người mẹ là ngôi đền thiêng liêng nhất nuôi dưỡng mầm sống tương lai.",
    "Dù mệt mỏi hay đau đớn, chỉ cần nghĩ đến ngày được bế con trên tay, mẹ lại có thêm sức mạnh phi thường.",
    "Hãy tận hưởng những ngày tháng thiêng liêng này, vì con yêu đang cùng mẹ trải qua những khoảnh khắc duy nhất.",
    "Một sinh linh bé nhỏ có thể lấp đầy khoảng trống lớn nhất trong trái tim người mẹ.",
    "Mẹ đang cùng con bước đi trên hành trình kỳ diệu của sự sống.",
    "Con yêu ơi, cả thế giới đang chờ đợi sự xuất hiện rực rỡ của con.",
    "Làm mẹ là khi bạn phát hiện ra những nguồn sức mạnh mà bạn chưa từng biết mình sở hữu.",
    "Hãy kiên nhẫn với chính mình, mẹ bầu nhé! Bạn đang làm một công việc tuyệt vời nhất thế gian.",
    "Từng tuần thai trôi qua là từng bước con đến gần hơn với vòng tay ấm áp của gia đình.",
    "Tình yêu của mẹ dành cho con đã bắt đầu từ trước khi mẹ nhìn thấy khuôn mặt con.",
    "Mỗi vết rạn da trên bụng mẹ đều là một huy chương danh dự của tình mẫu tử thiêng liêng.",
    "Hãy thở sâu, nghỉ ngơi và cảm nhận tình yêu thương bao la đang bao bọc lấy hai mẹ con.",
    "Em bé là minh chứng sống động nhất cho tình yêu đẹp đẽ của cha và mẹ.",
    "Mẹ bầu hạnh phúc sẽ sinh ra những em bé vui vẻ. Hãy luôn giữ nụ cười mẹ nhé!",
    "Hành trình nuôi dưỡng một sinh linh mới là bài ca đẹp nhất của tạo hóa.",
    "Mẹ sẵn sàng đánh đổi tất cả chỉ để đổi lấy sự bình an và khỏe mạnh của con yêu.",
    "Con là kết tinh của tình yêu, niềm hy vọng và những lời cầu nguyện chân thành nhất của cha mẹ.",
    "Hãy lắng nghe tiếng con máy trong bụng và mỉm cười, vì hai mẹ con đang trò chuyện bằng ngôn ngữ trái tim.",
    "Chào mừng con đến với thế giới đầy màu sắc này, ba mẹ đã sẵn sàng yêu thương con bằng cả cuộc đời.",
    "Hành trình làm mẹ là hành trình thiêng liêng nhất, chúc mẹ bầu luôn tràn đầy năng lượng tích cực và hạnh phúc!"
];
